services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: vacation_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: vacation_portal_db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vacation_phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:80"

  phpunit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vacation_phpunit
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["./vendor/bin/phpunit", "--display-incomplete", "--testdox", "--colors=always"]
    depends_on:
      - app
      - db

volumes:
  db_data:
